### ISSUE TITLE
Cannot access close code

### ISSUE THREAD

**Issue by mbonneau** [RxPHP/RxWebsocket#5]

**Comment by WyriHaximus** [comment]
Looking at this https://github.com/RxPHP/RxWebsocket/blob/e8846868b57ccb6851acf2344dc746fa9e10182c/src/Websocket/WebsocketFrameOperator.php#L60 there is a close code and it travels on error as an exception.

**Comment by mbonneau** [comment]
@WyriHaximus - I am planning on merging #4 if I can get someone to take a look at it. This will be a bigger change as it will primarily use https://github.com/ratchetphp/RFC6455 for the actual protocol now that all the updates have been merged over there.

I have pushed a commit to send any non-1000 error codes through to the error handler so that the code can be retrieved.

**Comment by WyriHaximus** [comment]
@mbonneau cool much appreciated, will review it shortly but it's a lot :P

**Comment by mbonneau** [comment]
@WyriHaximus - This change is available in the 0.10.0 release.

**Comment by WyriHaximus** [comment]
@mbonneau awesome, thank you 🎉
